const VITE_S3_ENDPOINT: string = window.VITE_S3_ENDPOINT || "";
const VITE_DB_ENDPOINT: string = window.VITE_DB_ENDPOINT || "";
const VITE_SQS_ENDPOINT: string = window.VITE_SQS_ENDPOINT || "";
const VITE_AWS_CLIENTID: string = window.VITE_AWS_CLIENTID || "";
const VITE_AWS_AUTHORITY: string = window.VITE_AWS_AUTHORITY || "";
const VITE_AWS_REDIRECTURI: string = window.VITE_AWS_REDIRECTURI || "";
const VITE_AWS_COGNITODOMAIN: string = window.VITE_AWS_COGNITODOMAIN || "";

export {
  VITE_S3_ENDPOINT,
  VITE_DB_ENDPOINT,
  VITE_SQS_ENDPOINT,
  VITE_AWS_CLIENTID,
  VITE_AWS_AUTHORITY,
  VITE_AWS_REDIRECTURI,
  VITE_AWS_COGNITODOMAIN,
};
